routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use function Ramsey\Uuid\v1;

Auth::routes();


Route::get('', function () {
    return redirect(route('index'));
});

Route::get('/home/{sort?}', 'EntryController@index')->name('index');
Route::get('entries/{id}/{sort?}', 'EntryController@entriesByUser')->name('userEntries');


Route::group(['middleware' => ['auth']], function () {
    
    Route::get('myEntries/', 'EntryController@userEntries')->name('myEntries');
    Route::get('profile', 'UserProfileController@profile')->name('profile');
    Route::post('profile', 'UserProfileController@updateProfile')->name('update_profile');

    Route::get('retrieveApiPosts/', 'RetievePosts@getPosts' )->name('retrieveApiPosts');

});

Route::resource( 'entry_action' ,EntryActionsController::class)->except([
    'update', 'destroy'
]);;

app/Entry.php
<?php

namespace App;

use App\Http\Traits\SortByTrait;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Entry extends Model
{

    use SortByTrait;

    protected $fillable = ['title', 'description'];
    private $request;

    public static function getEntries( Request $request, $id = null)
    {
        $order = SortByTrait::getSort($request) ? 'asc' : 'desc';
        $entries = is_null($id) ? Entry::orderBy('created_at', $order)
                : Entry::where("user_id", $id)->orderBy('created_at', $order);
        return $entries->get();
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getDateAndUserAttribute()
    {
        return $this->created_at." by ".$this->user->url;
    }

    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->rawFormat('M j, Y g:i:s A');
    }

    public function getContentAttribute($value)
    {
        return preg_replace("/\n\n/", "<br />", $value);
    }

    public function getContentPlainAttribute()
    {
        return str_replace('<br />', "\n", $this->content);
    }

}

resources/views/entries.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9 col-sm-3 blog-main">

                @guest
                @else
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif 
                @endguest

                @include('sort_by')

                @foreach ($entries as $entry)
                    <div class="blog-post">
                        <h2 class="blog-post-title">{{ $entry->title }}</h2>
                        <p class="blog-post-meta">{!!$entry->date_and_user !!}</p>
                        <p>{!!$entry->description!!}</p>
                    </div>
                @endforeach

                @include('sort_by')

            </div>
        </div>
    </div>
@endsection

resources/views/entry_actions.blade.php
{!! \App\Entry::printAction($entry) !!}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-9 col-sm-3">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/profile.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ $user->name }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('update_profile') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') ?? Auth::user()->name }}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') ?? Auth::user()->email }}" required autocomplete="email">

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Update') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sort_by.blade.php
<div class="row">
    <div class="col py-3 px-lg-5 bg-light align-middle">
        <a href="{{ $url }}" >Sort by created date <i class="align-middle fas {{ $iconDirection }}"></i></a> 
    </div>
</div>