routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use function Ramsey\Uuid\v1;

Auth::routes();


Route::get('', function () {
    return redirect(route('index'));
});

Route::get('/home/{sort?}', 'EntryController@index')->name('index');
Route::get('entries/{id}/{sort?}', 'EntryController@entriesByUser')->name('userEntries');


Route::group(['middleware' => ['auth']], function () {
    
    Route::get('myEntries/', 'EntryController@userEntries')->name('myEntries');
    Route::get('profile', 'UserProfileController@profile')->name('profile');
    Route::post('profile', 'UserProfileController@updateProfile')->name('update_profile');

    Route::get('retrieveApiPosts/', 'RetievePosts@getPosts' )->name('retrieveApiPosts');

});

Route::resource( 'entry_action' ,EntryActionsController::class)->except([
    'update', 'destroy'
]);;

app/Entry.php
<?php

namespace App;

use App\Http\Traits\SortByTrait;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Entry extends Model
{

    use SortByTrait;

    protected $fillable = ['title', 'description'];
    private $request;

    public static function getEntries( Request $request, $id = null)
    {
        $order = SortByTrait::getSort($request) ? 'asc' : 'desc';
        $entries = is_null($id) ? Entry::orderBy('created_at', $order)
                : Entry::where("user_id", $id)->orderBy('created_at', $order);
        return $entries->get();
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getDateAndUserAttribute()
    {
        return $this->created_at." by ".$this->user->url;
    }

    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->rawFormat('M j, Y g:i:s A');
    }

    public function getContentAttribute($value)
    {
        return preg_replace("/\n\n/", "<br />", $value);
    }

    public function getContentPlainAttribute()
    {
        return str_replace('<br />', "\n", $this->content);
    }

}

app/Http/Controllers/EntryController.php
<?php

namespace App\Http\Controllers;

use App\Entry;
use Illuminate\Http\Request;
use App\Http\Traits\SortByTrait;
use Illuminate\Support\Facades\Auth;

class EntryController extends Controller
{

    use SortByTrait;

    private $request;

    function __construct(Request $request)
    {
        $this->request = $request;
    }

    public function index()
    {
        return view('entries', [
                'entries' => Entry::getEntries($this->request),
                'url' => $this->getSortByUrl('index'),
                'iconDirection' => $this->getIconDirection($this->request),
        ]);
    }

    public function entriesByUser($id)
    {
        return view('entries', [
                'entries' => Entry::getEntries($this->request,$id),
                'url' => $this->getSortByUrl('userEntries',$id),
                'iconDirection' => $this->getIconDirection($this->request),
        ]);
    }

    public function userEntries(){
        return view('entries', [
                'entries' => Entry::getEntries($this->request, Auth::user()->id),
                'url' => $this->getSortByUrl('myEntries'),
                'iconDirection' => $this->getIconDirection($this->request),
        ]); 
    }
    
    
}

resources/views/entry/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9 col-sm-3 blog-main">
                <form action="{{ route('entry_action.store') }}" method="POST">
                    @csrf

                    <div class="form-group row">
                        <label for="title" class="col-md-2 col-form-label text-md-right">{{ __('Title') }}</label>
                        <div class="col-md-10">
                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" required autocomplete="name" autofocus>
                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="description" class="col-md-2 col-form-label text-md-right">{{ __('description') }}</label>
                        <div class="col-md-10">
                            <textarea id="description" type="text" class="form-control textarea_big @error('description') is-invalid @enderror" name="description" required>{{ old('description') }}</textarea>
                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-7 offset-md-5">
                            <button type="submit" class="btn btn-primary">
                                {{ __('Create') }}
                            </button>
                            <a class="btn btn-primary"  href="{{ route('myEntries') }}">
                                {{ __('View My Entries') }}
                            </a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection